commerce_product_variation.commerce_product_variation_type.*.third_party.commerce_autosku:
  type: mapping
  label: 'AutoSKU settings'
  mapping:
    mode:
      type: string
      label: 'Status'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: commerce_autosku.commerce_autosku_generator.plugin.[%parent.plugin]

commerce_autosku.commerce_autosku_generator.plugin.token:
  type: mapping
  mapping:
    pattern:
      type: string
      label: 'SKU replacement pattern'

